In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
counts = pd.read_csv('salmon.merged.numreads', sep='\t', header=0)

In [3]:
counts.head()

,Name,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,...,HM92_quant,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant
0,Sequence_16760413,1.0,3.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,Sequence_16760407,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Sequence_16760403,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Sequence_16760399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0
4,Sequence_16760397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
counts = counts.set_index('Name')

In [13]:
counts.head()

,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,HM111_quant,...,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant,rowSum
Name,,,,,,,,,,,,,,,,,,,,,
Sequence_16760413,1.0,3.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,19.0
Sequence_16760407,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Sequence_16760403,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,8.0
Sequence_16760399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,5.0
Sequence_16760397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [6]:
counts['rowSum'] = counts.sum(axis=1)

In [7]:
counts.head()

,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,HM111_quant,...,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant,rowSum
Name,,,,,,,,,,,,,,,,,,,,,
Sequence_16760413,1.0,3.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,19.0
Sequence_16760407,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
Sequence_16760403,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,8.0
Sequence_16760399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,5.0
Sequence_16760397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [8]:
counts['rowSum'].describe()

count    1.676041e+07
mean     1.114753e+02
std      4.227881e+04
min      0.000000e+00
25%      3.000000e+00
50%      5.000000e+00
75%      1.116500e+01
max      1.471233e+08
Name: rowSum, dtype: float64

In [9]:
counts[counts['rowSum'] == 0].count()/len(counts.index)

HM102_quant    0.001284
HM107_quant    0.001284
HM115_quant    0.001284
HM119_quant    0.001284
HM125_quant    0.001284
HM86_quant     0.001284
HM89_quant     0.001284
HM95_quant     0.001284
HM103_quant    0.001284
HM111_quant    0.001284
HM116_quant    0.001284
HM120_quant    0.001284
HM126_quant    0.001284
HM87_quant     0.001284
HM92_quant     0.001284
HM96_quant     0.001284
HM104_quant    0.001284
HM112_quant    0.001284
HM117_quant    0.001284
HM121_quant    0.001284
HM127_quant    0.001284
HM88_quant     0.001284
HM94_quant     0.001284
HM97_quant     0.001284
rowSum         0.001284
dtype: float64

In [10]:
counts_subset = counts[counts['rowSum'] > 1] 
counts_subset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15274281 entries, Sequence_16760413 to Sequence_12117687
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 3.0+ GB

In [11]:
counts.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16760414 entries, Sequence_16760413 to Sequence_12117687
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 3.2+ GB

In [12]:
counts_subset5 = counts[counts['rowSum'] > 5] 
counts_subset5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8358697 entries, Sequence_16760413 to Sequence_12117684
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 1.6+ GB

In [14]:
counts_subset5.to_csv("salmon.merged.numreads.subset5.csv")

In [15]:
tpm = pd.read_csv('salmon.merged.TPM', sep='\t', header=0)

In [16]:
tpm.head()

,Name,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,...,HM92_quant,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant
0,Sequence_16760413,0.078612,0.551171,0.337231,0.000000,0.631709,0.0,0.0,0.0,0.0,...,0.103717,0.0,0.0,0.155030,0.108585,0.0,0.000000,0.0,0.076642,0.000000
1,Sequence_16760407,0.000000,0.145305,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.123533,0.000000,0.0,0.000000,0.0,0.000000,0.000000
2,Sequence_16760403,0.000000,0.279845,0.000000,0.202869,0.000000,0.0,0.0,0.0,0.0,...,0.082162,0.0,0.0,0.118995,0.000000,0.0,0.000000,0.0,0.000000,0.100132
3,Sequence_16760399,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.349998,0.000000,0.0,0.130087,0.0,0.000000,0.098702
4,Sequence_16760397,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.343195,0.000000,0.0,0.000000,0.0,0.000000,0.000000

In [17]:
tpm = tpm.set_index('Name')
tpm.head()

,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,HM111_quant,...,HM92_quant,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant
Name,,,,,,,,,,,,,,,,,,,,,
Sequence_16760413,0.078612,0.551171,0.337231,0.000000,0.631709,0.0,0.0,0.0,0.0,0.103756,...,0.103717,0.0,0.0,0.155030,0.108585,0.0,0.000000,0.0,0.076642,0.000000
Sequence_16760407,0.000000,0.145305,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.123533,0.000000,0.0,0.000000,0.0,0.000000,0.000000
Sequence_16760403,0.000000,0.279845,0.000000,0.202869,0.000000,0.0,0.0,0.0,0.0,0.079373,...,0.082162,0.0,0.0,0.118995,0.000000,0.0,0.000000,0.0,0.000000,0.100132
Sequence_16760399,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.349998,0.000000,0.0,0.130087,0.0,0.000000,0.098702
Sequence_16760397,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.343195,0.000000,0.0,0.000000,0.0,0.000000,0.000000

In [18]:
counts5 = counts_subset5.index.tolist()
tpm5 = tpm.loc[counts5]

In [20]:
tpm5.head()

,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,HM111_quant,...,HM92_quant,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant
Name,,,,,,,,,,,,,,,,,,,,,
Sequence_16760413,0.078612,0.551171,0.337231,0.000000,0.631709,0.0,0.0,0.000000,0.000000,0.103756,...,0.103717,0.0,0.0,0.155030,0.108585,0.0,0.0,0.0,0.076642,0.000000
Sequence_16760403,0.000000,0.279845,0.000000,0.202869,0.000000,0.0,0.0,0.000000,0.000000,0.079373,...,0.082162,0.0,0.0,0.118995,0.000000,0.0,0.0,0.0,0.000000,0.100132
Sequence_16760389,0.000000,0.248940,0.000000,0.000000,0.000000,0.0,0.0,0.075081,0.000000,0.000000,...,0.000000,0.0,0.0,0.211515,0.000000,0.0,0.0,0.0,0.000000,0.000000
Sequence_16760388,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.069452,...,0.000000,0.0,0.0,0.414786,0.073407,0.0,0.0,0.0,0.000000,0.000000
Sequence_16760372,0.000000,0.000000,0.000000,0.000000,0.082408,0.0,0.0,0.000000,0.258822,0.000000,...,0.145788,0.0,0.0,0.101741,0.072095,0.0,0.0,0.0,0.000000,0.000000

In [21]:
counts_subset5.head()

,HM102_quant,HM107_quant,HM115_quant,HM119_quant,HM125_quant,HM86_quant,HM89_quant,HM95_quant,HM103_quant,HM111_quant,...,HM96_quant,HM104_quant,HM112_quant,HM117_quant,HM121_quant,HM127_quant,HM88_quant,HM94_quant,HM97_quant,rowSum
Name,,,,,,,,,,,,,,,,,,,,,
Sequence_16760413,1.0,3.0,3.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,19.0
Sequence_16760403,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,8.0
Sequence_16760389,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
Sequence_16760388,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,8.0
Sequence_16760372,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,9.0

In [19]:
tpm5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8358697 entries, Sequence_16760413 to Sequence_12117684
Data columns (total 24 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
dtypes: float64(24)
memory usage: 1.6+ GB

In [22]:
tpm5.to_csv("salmon.merged.TPM.subset5.csv")

In [13]:
keepgenes5 = list(counts_subset5.index)

In [14]:
with open(r'keepgenes5.txt', 'w') as fp:
    for item in keepgenes5:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [15]:
counts_subset10 = counts[counts['rowSum'] > 10] 
counts_subset10.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4632148 entries, Sequence_16760413 to Sequence_12117684
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 918.9+ MB

In [16]:
keepgenes10 = list(counts_subset10.index)

with open(r'keepgenes10.txt', 'w') as fp:
    for item in keepgenes10:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [17]:
counts_subset15 = counts[counts['rowSum'] > 15] 
counts_subset15.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3149803 entries, Sequence_16760413 to Sequence_12117684
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 624.8+ MB

In [18]:
keepgenes15 = list(counts_subset15.index)

with open(r'keepgenes15.txt', 'w') as fp:
    for item in keepgenes15:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [19]:
counts_subset20 = counts[counts['rowSum'] > 20] 
counts_subset20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2398981 entries, Sequence_16759618 to Sequence_12117684
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 475.9+ MB

In [20]:
keepgenes20 = list(counts_subset20.index)

with open(r'keepgenes20.txt', 'w') as fp:
    for item in keepgenes20:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [21]:
counts_subset25 = counts[counts['rowSum'] > 25] 
counts_subset25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1946221 entries, Sequence_16759618 to Sequence_13486293
Data columns (total 25 columns):
 #   Column       Dtype
---  ------       -----
 0   HM102_quant  float64
 1   HM107_quant  float64
 2   HM115_quant  float64
 3   HM119_quant  float64
 4   HM125_quant  float64
 5   HM86_quant   float64
 6   HM89_quant   float64
 7   HM95_quant   float64
 8   HM103_quant  float64
 9   HM111_quant  float64
 10  HM116_quant  float64
 11  HM120_quant  float64
 12  HM126_quant  float64
 13  HM87_quant   float64
 14  HM92_quant   float64
 15  HM96_quant   float64
 16  HM104_quant  float64
 17  HM112_quant  float64
 18  HM117_quant  float64
 19  HM121_quant  float64
 20  HM127_quant  float64
 21  HM88_quant   float64
 22  HM94_quant   float64
 23  HM97_quant   float64
 24  rowSum       float64
dtypes: float64(25)
memory usage: 386.1+ MB

In [22]:
keepgenes25 = list(counts_subset25.index)

with open(r'keepgenes25.txt', 'w') as fp:
    for item in keepgenes25:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [23]:
counts_subset30 = counts[counts['rowSum'] > 30] 
counts_subset30.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1643706 entries, Sequence_16759618 to Sequence_13486293
Data columns (total 25 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   HM102_quant  1643706 non-null  float64
 1   HM107_quant  1643706 non-null  float64
 2   HM115_quant  1643706 non-null  float64
 3   HM119_quant  1643706 non-null  float64
 4   HM125_quant  1643706 non-null  float64
 5   HM86_quant   1643706 non-null  float64
 6   HM89_quant   1643706 non-null  float64
 7   HM95_quant   1643706 non-null  float64
 8   HM103_quant  1643706 non-null  float64
 9   HM111_quant  1643706 non-null  float64
 10  HM116_quant  1643706 non-null  float64
 11  HM120_quant  1643706 non-null  float64
 12  HM126_quant  1643706 non-null  float64
 13  HM87_quant   1643706 non-null  float64
 14  HM92_quant   1643706 non-null  float64
 15  HM96_quant   1643706 non-null  float64
 16  HM104_quant  1643706 non-null  float64
 17  HM112_quant  1643706 non-null  float64
 18  HM117_quant  1643706 non-null  float64
 19  HM121_quant  1643706 non-null  float64
 20  HM127_quant  1643706 non-null  float64
 21  HM88_quant   1643706 non-null  float64
 22  HM94_quant   1643706 non-null  float64
 23  HM97_quant   1643706 non-null  float64
 24  rowSum       1643706 non-null  float64
dtypes: float64(25)
memory usage: 326.1+ MB

In [24]:
keepgenes30 = list(counts_subset30.index)

with open(r'keepgenes30.txt', 'w') as fp:
    for item in keepgenes30:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

below is for filtering based on presence in certain samples (from patrick's project)

In [11]:
incs = pd.read_csv('inc_samples.tsv', sep='\t', header=0)

In [13]:
incs.head()

  SampleName SampleID AssemblyGroup       FastqFile
0      DGGN1     HM11       inc_dgn  HM11_S112_L003
1      DSVN1     HM12       inc_dsn  HM12_S113_L003
2         N1     HM13         inc_n  HM13_S114_L003
3         N3     HM14         inc_n  HM14_S115_L003
4         B1     HM27         inc_c  HM27_S116_L003

In [14]:
counts.head()

,HM10_quant,HM14_quant,HM20_quant,HM26_quant,HM30_quant,HM34_quant,HM38_quant,HM43_quant,HM47_quant,HM51_quant,...,HM24_quant,HM29_quant,HM33_quant,HM37_quant,HM42_quant,HM46_quant,HM50_quant,HM54_quant,HM8_quant,rowSum
Name,,,,,,,,,,,,,,,,,,,,,
rnaspades_inc_dgn_NODE_2094027_length_144_cov_4.189474_g2048959_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.01
rnaspades_inc_dgn_NODE_2088779_length_152_cov_2.504854_g2043711_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.00
rnaspades_inc_dgn_NODE_2086731_length_152_cov_3.922330_g2041663_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.00
rnaspades_inc_dgn_NODE_2082539_length_153_cov_3.961538_g2037471_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.00
rnaspades_inc_dgn_NODE_2078379_length_154_cov_4.342857_g2033311_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.97

In [15]:
incs['SampleID'] = incs['SampleID'].astype(str) + '_quant'

In [16]:
incs.head()

  SampleName    SampleID AssemblyGroup       FastqFile
0      DGGN1  HM11_quant       inc_dgn  HM11_S112_L003
1      DSVN1  HM12_quant       inc_dsn  HM12_S113_L003
2         N1  HM13_quant         inc_n  HM13_S114_L003
3         N3  HM14_quant         inc_n  HM14_S115_L003
4         B1  HM27_quant         inc_c  HM27_S116_L003

In [17]:
inc_counts = counts[incs['SampleID']]
inc_counts.head()

,HM11_quant,HM12_quant,HM13_quant,HM14_quant,HM27_quant,HM28_quant,HM29_quant,HM30_quant,HM31_quant,HM32_quant,...,HM45_quant,HM47_quant,HM48_quant,HM49_quant,HM50_quant,HM51_quant,HM52_quant,HM53_quant,HM54_quant,HM64_quant
Name,,,,,,,,,,,,,,,,,,,,,
rnaspades_inc_dgn_NODE_2094027_length_144_cov_4.189474_g2048959_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rnaspades_inc_dgn_NODE_2088779_length_152_cov_2.504854_g2043711_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
rnaspades_inc_dgn_NODE_2086731_length_152_cov_3.922330_g2041663_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
rnaspades_inc_dgn_NODE_2082539_length_153_cov_3.961538_g2037471_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rnaspades_inc_dgn_NODE_2078379_length_154_cov_4.342857_g2033311_i0_inc_dgn_merged.fasta,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
inc_counts['rowSum'] = inc_counts.sum(axis=1)

/vortexfs1/apps/anaconda-5.1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [20]:
inc_counts.head()

,HM11_quant,HM12_quant,HM13_quant,HM14_quant,HM27_quant,HM28_quant,HM29_quant,HM30_quant,HM31_quant,HM32_quant,...,HM47_quant,HM48_quant,HM49_quant,HM50_quant,HM51_quant,HM52_quant,HM53_quant,HM54_quant,HM64_quant,rowSum
Name,,,,,,,,,,,,,,,,,,,,,
rnaspades_inc_dgn_NODE_2094027_length_144_cov_4.189474_g2048959_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.00
rnaspades_inc_dgn_NODE_2088779_length_152_cov_2.504854_g2043711_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.00
rnaspades_inc_dgn_NODE_2086731_length_152_cov_3.922330_g2041663_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,9.00
rnaspades_inc_dgn_NODE_2082539_length_153_cov_3.961538_g2037471_i0_inc_dgn_merged.fasta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.00
rnaspades_inc_dgn_NODE_2078379_length_154_cov_4.342857_g2033311_i0_inc_dgn_merged.fasta,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.97

In [22]:
inc_counts_subset25 = inc_counts[inc_counts['rowSum'] > 25] 
inc_counts_subset25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2552958 entries, rnaspades_inc_dgn_NODE_777099_length_259_cov_8.028571_g732043_i0_inc_dgn_merged.fasta to rnaspades_inc_dsn_NODE_53246_length_1787_cov_19.718642_g32392_i0_inc_dsn_merged.fasta
Data columns (total 30 columns):
 #   Column      Dtype
---  ------      -----
 0   HM11_quant  float64
 1   HM12_quant  float64
 2   HM13_quant  float64
 3   HM14_quant  float64
 4   HM27_quant  float64
 5   HM28_quant  float64
 6   HM29_quant  float64
 7   HM30_quant  float64
 8   HM31_quant  float64
 9   HM32_quant  float64
 10  HM33_quant  float64
 11  HM34_quant  float64
 12  HM35_quant  float64
 13  HM36_quant  float64
 14  HM37_quant  float64
 15  HM38_quant  float64
 16  HM39_quant  float64
 17  HM41_quant  float64
 18  HM42_quant  float64
 19  HM45_quant  float64
 20  HM47_quant  float64
 21  HM48_quant  float64
 22  HM49_quant  float64
 23  HM50_quant  float64
 24  HM51_quant  float64
 25  HM52_quant  float64
 26  HM53_quant  float64
 27  HM54_quant  float64
 28  HM64_quant  float64
 29  rowSum      float64
dtypes: float64(30)
memory usage: 603.8+ MB

In [23]:
inckeepgenes25 = list(inc_counts_subset25.index)

with open(r'inckeepgenes25.txt', 'w') as fp:
    for item in inckeepgenes25:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done

In [24]:
inc_counts_subset30 = inc_counts[inc_counts['rowSum'] > 30] 
inc_counts_subset30.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2242914 entries, rnaspades_inc_dgn_NODE_777099_length_259_cov_8.028571_g732043_i0_inc_dgn_merged.fasta to rnaspades_inc_dsn_NODE_53246_length_1787_cov_19.718642_g32392_i0_inc_dsn_merged.fasta
Data columns (total 30 columns):
 #   Column      Dtype
---  ------      -----
 0   HM11_quant  float64
 1   HM12_quant  float64
 2   HM13_quant  float64
 3   HM14_quant  float64
 4   HM27_quant  float64
 5   HM28_quant  float64
 6   HM29_quant  float64
 7   HM30_quant  float64
 8   HM31_quant  float64
 9   HM32_quant  float64
 10  HM33_quant  float64
 11  HM34_quant  float64
 12  HM35_quant  float64
 13  HM36_quant  float64
 14  HM37_quant  float64
 15  HM38_quant  float64
 16  HM39_quant  float64
 17  HM41_quant  float64
 18  HM42_quant  float64
 19  HM45_quant  float64
 20  HM47_quant  float64
 21  HM48_quant  float64
 22  HM49_quant  float64
 23  HM50_quant  float64
 24  HM51_quant  float64
 25  HM52_quant  float64
 26  HM53_quant  float64
 27  HM54_quant  float64
 28  HM64_quant  float64
 29  rowSum      float64
dtypes: float64(30)
memory usage: 530.5+ MB

In [25]:
inckeepgenes30 = list(inc_counts_subset30.index)

with open(r'inckeepgenes30.txt', 'w') as fp:
    for item in inckeepgenes30:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')

Done